### ISSUE TITLE
Clarify relevance of user groups

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#109]
Why are groups necessary ?

Intuitively _roles_ should be enough. Please show us the light, or we shall remove this notion :)

**Comment by Natim** [comment]
roles are specific to a model, group are specific to a daybed instance.

**Comment by leplatrem** [comment]
Are they useful ? If so, why ? Please give relevant use-cases in documentation. (Keep KISS in mind)

**Comment by Natim** [comment]
Let say your app need many models to work, you will want to create a group and set roles to that group so that all user of that group can have all the same roles on all of these models.

Then you can add people or remove them from that group.

You can also define an admin group to give access to models to all admins.

Then you can add users to the admin group and manage that group, you will know that all people in that group can manage all models.

**Comment by Natim** [comment]
Btw maybe we should add the group:admin to the roles:admin for all models.

**Comment by Natim** [comment]
Refs #113
