### ISSUE TITLE
Argue choice of setting permissions on HTTP verbs

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#110]
Permissions are currently expressed on HTTP verbs (get, put, post, delete).

Wouldn't it be easier and clearer to express permissions on user actions ?
- Create
- Read
- Modify
- Delete

_Create_ would be checked upon `POST` and `PUT`.

**Comment by Natim** [comment]
As you said, there is distinction between Create Read Update and Delete (that are the permission) and between the action.

For example for PUT you need three permissions R+U+D so you cannot do that.

**Comment by Natim** [comment]
As we said on IRC, there is permissions CRUD and there is permission needed by a view put_record, post_records etc.

**Comment by leplatrem** [comment]
But why couldn't we check the 3 permissions at the view level ?

I understand we're eager to reach 1.0, but I'd appreciate if we first clarify the concepts and technical argumentations. I suggest we close this issue when documentation on ACL is as clear as crystal !

**Comment by leplatrem** [comment]
Relates to #113

**Comment by leplatrem** [comment]
As far as I understand, there are two design problems related to this point : 
- The value of permission binary masks has a very strong dependance with the view code and behaviour. And this is far from being explicit.
- The permissions required are monolithic. For example, I wouldn't need the right to create users or policies if my user exists and if I use an existing policy for my model.

Couldn't we do something like this in views instead of having a single permission as decorator ? 

```
@record.put(validators=record_validator)
def put_record(...):
     if exists :
        if not (has_permission('read_record') and has_permission('update_record')):
             raise Unauthorized
     else:
        if not has_permission('create_record'):
             raise Unauthorized
```

I am no expert of pyramid patterns, so that's just a guess.

**Comment by almet** [comment]
Defining what are the allowed permissions on a record is IMO the best way to go, because this is not likely to change (e.g. if you've the right to delete a record, you probably don't want this to change).

Assigning a view permission (the string) to a number of operations on the model (retrieve, delete, create) allows to have everything factored somewhere we can refer ourselves to (and I think that's what you don't like).

I don't get your second example: if you already have an user and you use an existing policy for your model, you still may want to create new users and add them to groups. Can you explicit this part a bit more?

I like the idea behind the snippet you wrote: having the ACL behavior defined by a callable in the view itself make it simpler to grasp. But according to the pyramid docs, this shouldn't be handled here, but rather in the ACLPolicy, see http://docs.pylonsproject.org/projects/pyramid/en/latest/api/authorization.html

It seems that there are ways to let the ACLPolicy ask to the view some information (in the context), so maybe we could use this to let the permissions have a look at what's in the context before deciding if the user is authorized or not?

http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html contains some useful information about how all this work.

**Comment by leplatrem** [comment]
Indeed, I realize that some of my design interrogations may come from strong ignorance of pyramid patterns and concepts !

Regarding the two points I exposed : 
- The binary mask associated to a permission specifies what operations are required, according to what is executed in the view. Thus, I think that both notions should co-exist explicitly, rather than being a binary mask in `daybed.acl` and some code in `daybed.views`. I shall then take time to figure out what you mention about ACLPolicy and context :)
- When I say permission checking is monolithic, I mean that we check only one permission for the whole view, whereas we should check permissions atomically depending of the scenario within the view. For example, for model creation (`post_model`), we require creation on `definition`, `records`, `users` and `policy`. Why ? Can't I post a model if I am not allowed to create users and policies ?

**Comment by Natim** [comment]
As per #176 we have reworked the ACLS.
Why we should be using http verbs for acls? it is because you ask for a unique permission on a view, then the ACL engine is giving it or not.

You can see the mapping between the permissions we give to our users and the view permissions associated. Also having this table helps managing permissions all in the same place.

https://github.com/spiral-project/daybed/blob/master/daybed/acl.py#L63-L82

Please close this if it anwsers your question.

**Comment by almet** [comment]
I love how the new code makes things clearer :)

**Comment by leplatrem** [comment]
Thanks !
Maybe this clarification has a place in the project docs no ? (since it's related to the implementation, that may not be the case...)

Indeed, the code is much simpler :) I must admit I didn't catch exactly how to use it though :)

**Comment by Natim** [comment]
I tried something here: https://github.com/spiral-project/daybed/blob/patch_acls/docs/source/permissions.rst#views-permissions

Please add comments to improve it here: https://github.com/spiral-project/daybed/pull/185/files#diff-d09efa80d388b7d93ce21fb364d5fe5fR49
