### ISSUE TITLE
Faceted search of records

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#13]
http://www.elasticsearch.org does exactly what we need in terms of faceting (i.e. filters, drill down, ...)

Plus, it has a plugin to be fed from CouchDB : http://www.elasticsearch.org/guide/reference/river/couchdb.html

However I wonder how easy it could be deployed (ex: Heroku, Travis,...)

**Comment by ThomasG77** [comment]
Both Heroku and Travis support ElasticSearch 

Heroku way
https://devcenter.heroku.com/articles/bonsai#installing-the-addon

Travis way
http://about.travis-ci.org/docs/user/database-setup/

Infortunately, I haven't found if there are possibilities to use the CouchDB plugin on this two online hosting

**Comment by almet** [comment]
It seems that effectively Elastic Search does what we want, with faceting. http://www.elasticsearch.org/guide/reference/api/search/facets/

The river API could allow us to feed Elastic Search with data, and then we could define a higher-level to query the data, maybe depending on the data that has been stored, and its type, since we know what's its type (we have the description/schema for it).

Proposed flow:
- See how we can install the river plugin and make it index the data we put on CouchDB
- See which fields map to which facets
- Implement a search API on top of that.

**Comment by leplatrem** [comment]
Done :)
